### ISSUE TITLE
 Implementing Donation Tracker Form Validation and Testing 

### ISSUE THREAD

**Issue by Lsidhu8119** [Lsidhu8119/Community_Support_Tracker#1]
I am creating the Donation Tracker Component to keep tabs on donations to charities. This is started by  constructing a form with the following fields: Donor Comment/Message, Date of Donation, Charity Name, and Donation Amount. I am creating a JavaScript method that handles form submissions by storing information in a temporary object and validates inputs. Also i will write Jest tests as well to confirm that input validation and the form submission procedure work is done without error.

**Comment by Subhpreet855** [comment]
well done everything
